name: Maven Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adoptium'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings><servers><server><id>github</id><username>${{ secrets.MY_GITHUB_USERNAME }}</username><password>${{ secrets.GITHUBPACKAGE_TOKEN }}</password></server></servers></settings>' > ~/.m2/settings.xml

      - name: Build and deploy to GitHub Packages
        run: |
          mvn clean deploy -DskipTests
